export interface Photo {
  id: string;
  url: string;
  optimizedUrl?: string; // WebP optimized full-size version (generated by Cloud Function)
  thumbUrl?: string; // 200x200px thumbnail for grid view
  mediumUrl?: string; // 800x800px thumbnail for detail view
  title: string;
  description:string;
  path?: string; // Path in the bucket for deletion
  needsWebPRetry?: boolean; // 🏷️ Flag for photos that need WebP retry
}

export interface Album {
  id:string;
  title: string;
  coverPhotoUrl: string;
  photos: Photo[];
}

export interface NavLink {
  id: string;
  text: string;
  to: string;
}

export interface SeoSettings {
  metaTitle: string;
  metaDescription: string;
  metaKeywords: string;
  structuredData: string; // JSON-LD
}

export interface PreloaderSettings {
  enabled: boolean;
  style: 'modern' | 'minimal' | 'elegant' | 'animated' | 'glassmorphism';
  backgroundColor: string;
  primaryColor: string;
  secondaryColor: string;
  showLogo: boolean;
  showProgress: boolean;
  customText?: string;
  animationSpeed: 'slow' | 'normal' | 'fast';
}

export interface SiteSettings {
  appName: string;
  logoUrl: string | null;
  logoPath?: string; // Path in the bucket for deletion
  footerText: string;
  navLinks: NavLink[];
  gtmId: string;
  siteUrl?: string; // Custom site URL for sharing links
  seo: SeoSettings;
  aiEnabled?: boolean; // Enable/disable AI features
  geminiApiKey?: string; // Gemini API key for AI features
  preloader?: PreloaderSettings; // Preloader customization settings
}